Dev to test
doronmak/restaurants_api pull request #6
Opened 2020-10-10 11:33 UTC by doronmak

2020-10-10 12:02 UTC, bengabay11 requested changes
- create a dedicated folder for the source code
- how do you run the code in production?
- if some part of the code is with python annotations I recommend you to add the annotations in all your code

2020-10-10 12:02 UTC, bengabay11 commented on main.py
> +    uvicorn.run(app, host=config.api_host, port=config.port, log_level=config.log_level)
add future support for `ssl`

2020-10-10 12:02 UTC, bengabay11 commented on main.py
> +    first_app_init()
so you create the instance of the app in other file, and then import it?
why not move `first_app_init` to this file:
```pycon
app = first_app_init()
uvicorn.run(app, host=config.api_host, port=config.port, log_level=config.log_level)
```

2020-10-10 13:25 UTC, bengabay11 commented on app.py
> +async def post_restaurant(restaurant: Restaurant):
```suggestion
async def post_restaurant(restaurant: Restaurant) -> JSONResponse:
```

2020-10-10 13:48 UTC, bengabay11 commented on requirements.txt
> +uvicorn~=0.12.1
you need dev requirements file. you can use `pipenv` to manage that.

2020-10-11 08:45 UTC, doronmak commented on app.py
> +class Restaurant(BaseModel):
Done

2020-10-11 08:45 UTC, doronmak commented on app.py
> +@app.post('/restaurant')
Done

2020-10-11 08:45 UTC, doronmak commented on app.py
> +    return "post new restaurant"
Done

2020-10-11 08:45 UTC, doronmak commented on config.py
> +api_host = "localhost"
Done

2020-10-11 08:49 UTC, doronmak commented on database/models.py
> +class Restaurants(Base):
Done

2020-10-11 08:49 UTC, doronmak commented on requirements.txt
> +pydantic~=1.6.1
ok

2020-10-11 18:49 UTC, closed without merging